plugin:
    name: 'numencode.widgets::lang.plugin.name'
    description: 'numencode.widgets::lang.plugin.description'
    author: 'Blaz Orazem'
    icon: oc-icon-briefcase
    homepage: 'https://github.com/numencode/widgets-plugin'
navigation:
    widgets:
        label: 'numencode.widgets::lang.plugin.name'
        url: numencode/widgets/promotions
        icon: icon-briefcase
        permissions:
            - manage_widgets
        order: '399'
        sideMenu:
            promotions:
                label: 'numencode.widgets::lang.promotions.name'
                url: numencode/widgets/promotions
                icon: icon-th-large
                permissions:
                    - manage_promotions
            highlights:
                label: 'numencode.widgets::lang.highlights.name'
                url: numencode/widgets/highlights
                icon: icon-star
                permissions:
                    - manage_highlights
            features:
                label: 'numencode.widgets::lang.features.name'
                url: numencode/widgets/features
                icon: icon-eye
                permissions:
                    - manage_features
permissions:
    manage_promotions:
        tab: 'numencode.widgets::lang.plugin.name'
        label: 'numencode.widgets::lang.permissions.promotions'
    manage_highlights:
        tab: 'numencode.widgets::lang.plugin.name'
        label: 'numencode.widgets::lang.permissions.highlights'
    manage_features:
        tab: 'numencode.widgets::lang.plugin.name'
        label: 'numencode.widgets::lang.permissions.features'