list: $/numencode/widgets/models/featuregroup/columns.yaml
modelClass: NumenCode\Widgets\Models\FeatureGroup
title: 'numencode.widgets::lang.features.name'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'numencode/widgets/features/update/:id'
