list: $/numencode/widgets/models/promotiongroup/columns.yaml
modelClass: NumenCode\Widgets\Models\PromotionGroup
title: 'numencode.widgets::lang.promotions.name'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'numencode/widgets/promotions/update/:id'
